name: nested_set

services:
  composer-dev:
    container_name: composer
    build:
      context: ./
      dockerfile: deploy/Dockerfile
    volumes:
      - ./:/var/www

  nested-service-dev:
    container_name: nested-service
    build: 
      context: ./
      dockerfile: deploy/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=nested-service
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
    env_file:
      - ./.env
    volumes:
      - ./src:/var/www/
    user: '33:33'
    ports:
      - 8000:80
    depends_on:
      mysql:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  mysql:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - ./.env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./deploy/mysql-init:/docker-entrypoint-initdb.d/
    restart: always
    ports:
        - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      interval: 10s
      retries: 10
      start_period: 40s


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql
secrets:
  mysql_password:
    file: deploy/secrets/mysql_password.txt

volumes:
  mysql-data:
