FROM mysql

ENV MYSQL_ROOT_PASSWORD=root \
        MYSQL_DATABASE=docebo \
        MYSQL_USER=user \
        MYSQL_PASSWORD=password
COPY sql/tables.sql /docker-entrypoint-initdb.d/1.sql
COPY sql/data.sql /docker-entrypoint-initdb.d/2.sql

EXPOSE 3306