insert into `node_tree`(idNode,level, iLeft,iRight)
values(null,2,2,3),
(null,2,4,5),
(null,2,6,7),
(null,2,8,9),
(null,1,1,24),
(null,2,10,11),
(null,2,12,19),
(null,3,15,16),
(null,3,17,18),
(null,2,20,21),
(null,3,13,14),
(null,2,22,23);

insert into `node_tree_names`(idNode,language,nodeName)
values(1,'english','Marketing'),
(1,'italian','Marketing'),
(2,'english','Helpdesk'),
(2,'italian','Supporto Tecnico'),
(3,'english','Managers'),
(3,'italian','Managers'),
(4,'english','Customer Account'),
(4,'italian','Assistenza Cliente'),
(5,'english','Docebo'),
(5,'italian','Docebo'),
(6,'english','Accounting'),
(6,'italian','Amministrazione'),
(7,'english','Sales'),
(7,'italian','Supporto vendite'),
(8,'english','Italy'),
(8,'italian','Italia'),
(9,'english','Europe'),
(9,'italian','Europa'),
(10,'english','Developers'),
(10,'italian','Sviluppatori'),
(11,'english','North America'),
(11,'italian','Nord America'),
(12,'english','Quality Assurance'),
(12,'italian','Controllo qualità');